[tox]
envlist = py38

[pytest]
norecursedirs= venv build env bin .cache .tox coverage dist downloads *.egg-info
minversion = 6.2

[flake8]
max_line_length = 100
exclude = migrations,env,bin,venv,build,.tox,.cache, .git, {{cookiecutter.host_name}}/

[testenv]
deps = -rrequirements.txt
commands =
    flake8 bot config tests main.py
    coverage erase
    coverage run -m pytest tests
    coverage html
    coverage report --fail-under 100
sitepackages = False
